fluentd_logger/managed_vms.conf

R: @apolito CC: @dlorenc @liqianluo

Add nginx access logs, with support for traceId if found.

---

api_proxy/Dockerfile
api_proxy/proxy.go
api_proxy/proxy_test.go

For now, return an errorfor all requests.

Add an api-proxy for moving off the Service Bridge.

---

fluentd_logger/Dockerfile

This resolves a build issue with a transitive dependency in 0.4.4.
+R @jonparrott

Update fluent-plugin-google-cloud to 0.5.2

---

nginx_proxy/Dockerfile
nginx_proxy/start_nginx.sh

1. Install cron so that log rotation can work.
2. Optionally accept Service Name and Service Version as parameters for
Endpoints Server Proxy.

Update the nginx Docker image.

---

fluentd_logger/managed_vms.conf

R: @andrewsg 
Open question of whether the tag renaming should be separate, or if there are hidden dependencies on the tag name that I should address.

Error logging and tag renaming for nginx logs.

---

fluentd_logger/managed_vms.conf

Tag all log entries with instance name label

---

fluentd_logger/managed_vms.conf

R: @andrewsg 
This is done so we can report aggregate stats for health check statuses.

Save nginx health checks to a local file

---

api_verifier/api_verifier.py

Increase api_verifier timeout from 2 minutes to 15 minutes.

---

fluentd_logger/out_from_docker.rb

Update plugin to fluentd 0.14 API

---

fluentd_logger/Dockerfile

Upgrade fluent-plugin-google-cloud to 0.6

---

fluentd_logger/managed_vms.conf

Adding the new categories of health checks.
+R @karan 
+R @andrewsg

Add support for liveness and readiness checks

---

metadata_watcher/Dockerfile
metadata_watcher/metadata_watcher.py

Adds a new agent to long-poll metadata changes.
R: @josephburnett
R: @andrewsg

Add metadata watcher

---

fluentd_logger/managed_vms.conf

They show up in nginx.requests currently.
R: @andrewsg 
CC: @andrerod

Include /_ah/vm_health in nginx.health_check logs

---

fluentd_logger/managed_vms.conf

Preserve instance name even with httpRequest log entries.

---

CONTRIBUTING.md

1. Update lists to use four-space indents.
2. Fix links. ((text) [url] -> (text)[url])
+R @rdcastro

Update CONTRIBUTING.md to conform to Google markdown style guide

---

fluentd_logger/managed_vms.conf

Log the actual traceId instead of the string '$traceId'

---

.travis.yml
fluentd_logger/managed_vms.conf

Modified x-forwarded-for regex so that it matches "-" (but does not set realClientIp in this case) so that the subsequent upstreamLatencySeconds group can be matched.

Fluentd should parse upstream latency.

---

iap_watcher/iap_watcher.py

Thanks for catching this, Jon!

Query project instead of instance metadata.

---

fluentd_logger/Dockerfile

Update fluentd plugin to 0.6.8 version

---

nginx_proxy/start_nginx.sh

Reverts GoogleCloudPlatform/appengine-sidecars-docker#83
This causes the nginx container to bootloop and deployments to fail.

Revert dfe0124a3: "Used the start_esp to run nginx (#83)"

---

fluentd_logger/managed_vms.conf

This will show up as e.g. "HTTP/1.1" or "websocket".

Start logging protocol in the httpRequest proto

---

fluentd_logger/Dockerfile

This picks up
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/203

Update fluent-plugin-google-cloud to 0.6.13

---

fluentd_logger/managed_vms.conf

Fixes https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/89.

Enable JSON detection in text logs.

---

iap_watcher/Dockerfile

Tested build with Cloud Container Builder service, it worked.

Run command that assumes bash with bash

---

fluentd_logger/Dockerfile
fluentd_logger/managed_vms.conf

This contains the fix for duplicate logs.

Update fluent-plugin-google-cloud to 0.6.25.1

---

opentelemetry_collector/receiver/dockerstats/scraper.go
opentelemetry_collector/receiver/dockerstats/scraper_test.go

ATM, we don't care about breaking down these stats per networkinterface, hence
these are aggregated at container level.

Track container network stats.

---

stackdriver_monitoring_agent/Dockerfile
stackdriver_monitoring_agent/cloudbuild.yaml

Changed base image from Debian 9 to Debian 10.
Switched from OpenJDK8 to OpenJDK11 for JVM monitoring.

Changed base image for Monitoring Agent

---

iap_watcher/Dockerfile
iap_watcher/cloudbuild.yaml
iap_watcher/iap_watcher.py
iap_watcher/iap_watcher_test.py
iap_watcher/test.sh

Switched base image to Debian 10
Switched Python interpreter to Python 3

Switched base image of IAP watcher to Debian 10 and Python interpreter to Python3

---

opentelemetry_collector/opentelemetry_config.yaml

update internal container metrics to prefix with agent

update internal container metrics to prefix with agent
