fluentd_logger/managed_vms.conf

R: @apolito
Accidentally left this improvement out of the original PR. Sorry!

Fix nginx access regex to accept punctuation in tracecontext options

---

nginx_proxy/proxy_pass.inc

This more than doubles performance during a standalone test of wrk against an
nginx proxying to a Go hello world application running on the same server.
Although this doesn't have such a drastic effect on performance due to slower links in the chain today, this eradicates load and bottlenecks for future versions.

Use HTTP 1.1 to connect to the application servers

---

api_verifier/api_verifier.py

The call to modules.get_num_instances() can, in some cases, take much longer than a second.
While here, update the copyright to something reasonable (first commit to the file) and other small cleanups.

Base 2 minute timeout on elapsed time

---

fluentd_logger/Dockerfile

Added build-essential to list of apt-get install packages.
We need "make" to build native extensions.  Not sure how this worked before.  Maybe the base image used to include it.

Added build-essential

---

fluentd_logger/Dockerfile
fluentd_logger/managed_vms.conf

R: @jonparrott 
This opens port 24224 and listens on it for app container logs. Logs that come in with the tag "app-container" are rewritten so that the tag is equal to the source stream (stdout or stderr) to emulate existing behavior.
Changes on the VM agent are required to use this functionality. The old logging functionality is intact so that this fluentd image will be backwards-compatible with older VM agents.

Expose an HTTP socket to receive app container logs

---

memcache_proxy/dtog.go
memcache_proxy/dtog_test.go

Some clients use `Memcached::getVersion` to determine if the server is running and the connection is working.  The current implementation [throws an error](https://github.com/GoogleCloudPlatform/appengine-sidecars-docker/blob/master/memcache_proxy/dtog.go#L250), which results in clients making the mistaken assumption the server is not responding.
This PR adds support for the [version](https://github.com/memcached/memcached/blob/1.2.4/doc/protocol.txt#L422) protocol command, but returns "not implemented". This allows the client to verify the connection is successful, but does not return any actual versioning information since we do not actually have a version number.
**Usage**
```
$ telnet <proxy-ip> <proxy-host>
Trying <proxy-ip>...
Connected to <proxy-ip>.
Escape character is '^]'. …
```

memcache_proxy: return "App Engine" for "version"

---

fluentd_logger/managed_vms.conf

R: @andrewsg 
This allows us to send sub-second granular logs, despite the limitations of the version of fluentd currently used by google-fluentd.
Logs before and after the change to nginx config pushed out with the vm image need to be parseable.
Sample log before change:
172.17.0.1 - - [23/Aug/2016:01:57:20 +0000] "GET /_ah/health HTTP/1.1" 200 2 "-" "curl/7.26.0" tracecontext="-"
Sample log after change:
172.17.0.1 - - [23/Aug/2016:01:57:20 +0000] "GET /_ah/health HTTP/1.1" 200 2 "-" "curl/7.26.0" tracecontext="-" timestampSeconds="1471917440.683000000"

Add regex to parse time from the $msec directive of nginx.

---

fluentd_logger/Dockerfile
fluentd_logger/managed_vms.conf

Reverts GoogleCloudPlatform/appengine-sidecars-docker#15
Due to possible stability regressions from routing Docker logs directly to fluentd, we're rolling this feature back. It's not important that this rollback be picked up in a timely fashion because the business logic is elsewhere; this is just cleanup of a now unexposed feature.
R: @Cynocracy

Revert "Expose an HTTP socket to receive app container logs"

---

fluentd_logger/managed_vms.conf

R: @andrewsg 
Last change to the fluentd regex from me. Both of the below (and one with either timestampSeconds/latency and not the other, although that case is unexpected) should parse fine.
Sample log before change:
172.17.0.1 - - [23/Aug/2016:01:57:20 +0000] "GET /_ah/health HTTP/1.1" 200 2 "-" "curl/7.26.0" tracecontext="-"
Sample log after change:
172.17.0.1 - - [23/Aug/2016:01:57:20 +0000] "GET /_ah/health HTTP/1.1" 200 2 "-" "curl/7.26.0" tracecontext="-" timestampSeconds="1471917440.683000000" latencySeconds="0.003"

Add regex to parse time from the $request_time directive of nginx.

---

fluentd_logger/managed_vms.conf

R: @andrewsg 
Loglevel, pid, and tid were previously hidden in the cloud logging UI, this should surface them in a more user-friendly way for now (by simply including them in the message).
As nginx uses non-standard log levels, we shouldn't just output it as (?<severity>), which would normally be the right and proper way to go about it.

Update fluentd config for nginx.error.

---

fluentd_logger/managed_vms.conf

R: @andrewsg 
This allows users to distinguish between health checks and actual accesses.

Filter health check requests into a separate tag.

---

fluentd_logger/managed_vms.conf

Rename syslog -> vm.syslog as part of log tag cleanup.

---

fluentd_logger/Dockerfile

+R: @rdcastro 
No need to rush to get this built. By coincidence our latest build (any image after 2017-01-07) does not suffer from the problem due to an upstream rollback. We can simply pick this up in our next security update build for future-proofing.

Remove fluentd plugin version pin

---

fluentd_logger/managed_vms.conf

+R @rdcastro 
This will allow us to add additional data like x-forwarded-for to the nginx config without having to update fluentd in lockstep (safer rollouts).

Make fluentd accept nginx access logs with unrecognized additional data at the end of a line

---

fluentd_logger/managed_vms.conf

This is a backwards-compatible change (if X-Forwarded-For is not present in the logs, the log format stays the same).
+R @jkh52

Parse X-Forwarded-For header from access logs to determine real IP.

---

fluentd_logger/Dockerfile
fluentd_logger/managed_vms.conf

Reverts GoogleCloudPlatform/appengine-sidecars-docker#41
Need to revert this as it's incompatible with Fluentd 0.14.x and causing a worker process reboot loop:
/opt/google-fluentd/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate fluent-plugin-detect-exceptions-0.0.4, because fluentd-0.14.8 conflicts with fluentd (<= 0.13, ~> 0.10) (Gem::ConflictError)
cc: @thomasschickinger

Revert "Add plugin to detect exceptions in stdout/stderr and log them in one log entry"

---

fluentd_logger/Dockerfile
fluentd_logger/managed_vms.conf

v0.0.5 of the plugin has removed the upper bound on the fluentd version and is compatible with every 0.1x version of fluentd.

Reenable detect exception plugin and switch version to 0.0.5.

---

metadata_watcher/Dockerfile

Adds RUN mkdir command before WORKDIR command in Dockerfile because WORKDIR command in  the version of Docker used by Jenkins does not create dir recursively.
R: @josephburnett

Add mkdir command

---

cloud_sql_proxy/build.sh

This includes a fix for domain-scoped project IDs.

cloud_sql_proxy: update to 1.10

---

fluentd_logger/managed_vms.conf

1. Make it not all on one line.
2. Remove appLatencySeconds, since httpRequest is turned into an
HttpRequest proto, which does not have an app_latency_seconds field.
(appLatencySeconds is included as a generic key in the JsonPayload
object due to its intry in the the "keep_keys" tag.)

Clean up httpRequest proto

---

iap_watcher/Dockerfile
iap_watcher/iap_watcher.py
iap_watcher/iap_watcher_test.py

1. Install curl so that keys can actually be fetched
2. Move initial key fetch from build time to container start time
Testing:
- Unit tests pass.
- Built and started container locally; initial key fetch occurred as expected.

Fix IAP watcher

---

fluentd_logger/managed_vms.conf

This change increases the number of threads available to fluentd to 8 per https://docs.fluentd.org/v0.12/articles/out_file. 
Using more than 1 thread is a recommendation when the destination of the logs is remote - as is Flex's scenario where we upload our logs to a service.
More details in (e.g.):
https://blog.treasuredata.com/blog/2015/08/18/5-tips-to-optimize-fluentd-performance/

#63701884: Increase fluentd num threads to 8

---

iap_watcher/iap_watcher.py
iap_watcher/iap_watcher_test.py

Prevents the container from crashing if the metadata doesn't parse as valid JSON or the resulting JSON object doesn't contain the key 'enabled'.

Bulletproof metadata parsing

---

fluentd_logger/Dockerfile

0.6.8 may have been impacted by a memory leak issue: see https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/196

Update fluent-plugin-google-cloud to 0.6.12

---

third_party/iap_jwt_verify_nginx/src/jwt.cc

This PR fixes the ESP build error on gLinux Rodete
$ g++ --version
g++ (Debian 6.3.0-18) 6.3.0 20170516
ERROR: /usr/local/google/home/jaebong/.cache/bazel/_bazel_jaebong/2d2a51155bb03044e06c3369c2128c3e/external/iap_jwt_verify_nginx/third_party/iap_jwt_verify_nginx/src/BUILD:63:1: C++ compilation of rule '@iap_jwt_verify_nginx//third_party/iap_jwt_verify_nginx/src:iap_jwt_verification' failed (Exit 1).
external/iap_jwt_verify_nginx/third_party/iap_jwt_verify_nginx/src/jwt.cc: In static member function 'static std::unique_ptr<google::cloud::iap::Jwt> google::cloud::iap::Jwt::parse_from_string(const string&)':
external/iap_jwt_verify_nginx/third_party/iap_jwt_verify_nginx/src/jwt.cc:77:12: error: could not convert 'false' from 'bool' to 'std::unique_ptr<google::cloud::iap::Jwt>'
return …

Fixed return datatype incompatibility

---

nginx_proxy/start_nginx.sh

In the GAE Flex environment, the real client IP address is located at the second from the last of the X-Forwarded-For header.
To extract client IP address, ESP introduced new arguments --client_ip_header and --client_ip_position.
Required version of endpoints-runtime is 1.15.0 or later.

Added start_esp argument to extract the second to the last part of X-Forwarded-For header

---

BUILD

This is required by Google open source licensing policies.

Add exports_files(["LICENSE"]) directive to root BUILD file

---

iap_watcher/Dockerfile
iap_watcher/cloudbuild.yaml

This adds a cloudbuild.yaml file and updates the Dockerfile so that we
can build this using Google Container Builder.
container builds submit.
See also #101.

iap-watcher: add cloudbuild.yaml + update Dockerfile for GCB

---

fluentd_logger/Dockerfile
fluentd_logger/cloudbuild.yaml

This adds a cloudbuild.yaml file and updates the Dockerfile so that we
can build this using Google Container Builder.
container builds submit.
See also #101.

fluentd-logger: add cloudbuild.yaml + update Dockerfile for GCB

---

nginx_proxy/Dockerfile
nginx_proxy/cloudbuild.yaml

This adds a cloudbuild.yaml file and updates the Dockerfile so that we
can build this using Google Container Builder.
container builds submit.
See also #101.

nginx-proxy: add cloudbuild.yaml + update Dockerfile for GCB

---

api_proxy/cloudbuild.yaml

This adds a cloudbuild.yaml file and so that we can build this using
Google Container Builder.
container builds submit. It also builds the go binary used by the Docker
container.
See also #101.

api-proxy: add cloudbuild.yaml file for GCR

---

cloud_sql_proxy/cloudbuild.yaml

This adds a cloudbuild.yaml file and so that we can build this using
Google Container Builder.
container builds submit.
It also builds the go binary used by the Docker container, which is
pinned to a specific commit.
See also #101.

cloudsql-proxy: add cloudbuild.yaml file for GCR

---

memcache_proxy/Dockerfile.builder
memcache_proxy/build.sh
memcache_proxy/cloudbuild.yaml

This adds a cloudbuild.yaml config file as well as a custom Dockerfile
to specify the build environment for this sidecar so that we can build
it with Google Container Builder.
container builds submit. It also builds a special container used to run
the `build.sh` script, but this container is not saved externally.
Also, I updated the `build.sh` script to use `mktemp -d` instead of
`--directory` because the version of `mktemp` that container builder
uses doesn't support `--directory`. This should be backwards compatible.

memcache-proxy: add cloudbuild.yaml + custom Dockerfile.builder for GCR

---

base/Dockerfile
base/cloudbuild.yaml

This is the coveted gcr.io/google-appengine/base that some of the other
Docker images depends on.

Add Dockerfile + cloudbuild.yaml for base Docker image

---

memcache_proxy/build.sh
memcache_proxy/cloudbuild.yaml

We need to compile with these flags, which aren't the default for Container Builder.
This whole things is pretty hacky, so I just added the workaround of least resistance:
manually building the binary again after running the build.sh script.

Fix binary arch issue in memcache-proxy

---

iap_watcher/Dockerfile

This is to avoid hammering on the IAP key endpoint synchronously once-per-hour.

Fetch keys at a random time per-VM

---

.travis.yml

Neither of the golang versions here are supported anymore, so let's update.

Update GO_VERSION to stop Travis flakes

---

iap_watcher/Dockerfile

https://stackoverflow.com/questions/46235982/why-doesnt-service-cron-start-work-within-the-docker-file
Tested this new version; it behaves as expected.

 Move "service cron start" into ENTRYPOINT

---

fluentd_logger/managed_vms.conf

Log logging.googleapis.com/trace field to enable Stackdriver tracing features for ngnix request logs. Keep existing traceId field untouched in order to keep backward compatibility.

Log logging.googleapis.com/trace field to enable Stackdriver tracing features

---

nginx_proxy/Dockerfile

gcr.io/google-appengine/base uses debian8 as its base, which is EOL. This is causing this dockerfile to fail to build on apt-get. This debian9 image should contain everything needed to be a drop in replacement for base.

Use debian9 as base image instead of base.

---

opentelemetry_collector/opentelemetry_config.yaml

dockerstats metrics are intended for a different prefix than VM Image
age metrics. Eventually, they'd be written to
appengine.googleapis.com/flex/instance/, but until ACLs allow for it,
write them to custom.googleapis.com/flex/instance instead.

Separate metrics pipeline for dockerstats.

---

opentelemetry_collector/opentelemetry_config.yaml

Usage of custom.googleapis.com is not free. As we get ready to rollout the collector on Flex, we want to make sure that we don't accidentally roll it out in the wrong domain and cause billing issues.

Update metric prefix for stackdriver/instance

---

opentelemetry_collector/receiver/dockerstats/scraper.go
opentelemetry_collector/receiver/dockerstats/scraper_test.go

docker stats API doesn't expose CPU limit directly, so we have to extract it from the config.
There are multiple ways to set it when executing `docker run`, which makes the current approach a little fragile. Fortunately, we use the same way (setting `--cpus`) across different containers.

Add container CPU stats as metrics.

---

opentelemetry_collector/go.mod
opentelemetry_collector/receiver/dockerstats/factory.go
opentelemetry_collector/receiver/dockerstats/scraper.go
opentelemetry_collector/receiver/dockerstats/scraper_test.go

Fixes #147.
Opentelemetry already uses zap logger for various other components. We
simply plumb it through to dockerstats scraper and use it there.

Use zap.Logger instead of glog.

---

opentelemetry_collector/go.mod
opentelemetry_collector/receiver/dockerstats/scraper.go
opentelemetry_collector/receiver/dockerstats/scraper_test.go
opentelemetry_collector/receiver/metricgenerator/metric_generator.go
opentelemetry_collector/receiver/metricgenerator/metric_generator_test.go

This was recommended by the Stackdriver team to keep it consistent with
CPU usage metrics across GCP.

Switch CPU metrics to use "seconds" as unit.

---

opentelemetry_collector/components.go
opentelemetry_collector/go.sum
opentelemetry_collector/opentelemetry_config.yaml
opentelemetry_collector/receiver/vmagereceiver/config.go
opentelemetry_collector/receiver/vmagereceiver/config_test.go
opentelemetry_collector/receiver/vmagereceiver/doc.go
opentelemetry_collector/receiver/vmagereceiver/factory.go
opentelemetry_collector/receiver/vmagereceiver/factory_test.go
opentelemetry_collector/receiver/vmagereceiver/metrics_receiver.go
opentelemetry_collector/receiver/vmagereceiver/testdata/config.yaml
opentelemetry_collector/receiver/vmagereceiver/vm_image_age_collector.go
opentelemetry_collector/receiver/vmagereceiver/vm_image_age_collector_test.go
opentelemetry_collector/receiver/vmagereceiver/vm_image_age_constants.go
opentelemetry_collector/receiver/vmimageagereceiver/doc.go

Preparation for adding more VM age related metrics.

Rename vmimageagereceiver to vmagereceiver. 
